### ISSUE TITLE
release-log.txt file misses 2.2.1 & 2.2.2 features/fixes

### ISSUE THREAD

**Issue by tucu00** [YahooArchive/oozie#137]

**Comment by rvs** [comment]
Strictly speaking it doesn't:

http://github.com/yahoo/oozie/blob/2.2/release-log.txt

The trouble is that the commit which introduced those things sits 
on top of actual 2.2.1 and 2.2.2 release points:

http://github.com/yahoo/oozie/commit/e76b0e5babf71926f12c37ab0df65dfd2626b60e

That said, at this point it would be pretty much impossible to splice things
in, since we depend on the 2.2 branch the way it is.

Moving forward, I'll be using a modified maven release plugin to take care
of release-log.txt

Anyway, I'm tempted to close this, as an unfortunate WILL NOT FIX,
but if you have good ideas on how to fix it -- I'm all ears.

Please let me know.

**Comment by rvs** [comment]
Closed by c5fa1f6787909c3ecc02c2254a74a8e6fa2808a4 release-log.txt file misses 2.2.1 & 2.2.2 features/fixes
