### ISSUE TITLE
Authentication module for oozie

### ISSUE THREAD

**Issue by bansalmayank** [YahooArchive/oozie#332]
As Oozie is the workflow engine on the gateway, it has to be integrated with all other grid systems in order to run jobs and compliant with their authentication policy. Oozie should authenticate those users and propagate credentials (i.e delegation tokens) to the tasks through job conf by that they can be used by the tasks to authenticate themselves against those systems while running.

We need one unified interface for user by which they can specify what all the systems they want to use and authenticate against and should be able to provide configuration for authentication.

**Comment by brookwc** [comment]
Closed by eb21a642a629d016d5ac0cdabfb24e30c3c09324 Adding Credentials Module.

**Comment by bansalmayank** [comment]
Adding the Discussion thread....

I think that makes sense. 

-Andreas.

On Feb 17, 2011, at 10:32 AM, Alejandro Abdelnur wrote:

On #2,

but why not have the credentials in the extension itself? For example:

<action name="myaction">
  <authentication credentials="cred1,cred2" xmlns="uri:oozie:credentials">
    ...
  </authentication>
  <map-reduce> ... </map-reduce>
</action>

Thanks.

Alejandro

On Thu, Feb 17, 2011 at 12:55 PM, Angelo Kaichen Huang angeloh@yahoo-inc.com wrote:

On #1, you are right.
On #2, we have to let each action declare which credentials they need, we have to something like that.

<action cred=”cred1, cred2”>
</action>

Therefore current schema has to be changed to add this attribute to action element. That’s the reason for us to create a new schema instead of doing extension.

Thanks,
Angelo

On 2/15/11 6:43 PM, "Alejandro Abdelnur" tucu@cloudera.com wrote:

On #1, that info is in the action XML already, correct? if so you don't need to store it again.

On #2, the WF schema does not care of what goes in the extension schema, so changes in the extension schema do not affect the WF schema. That is the whole point of using extensions. Regarding taking it later, once you go live with this you'll have to support whatever schema changes you did, because of that I think we should do this right from the get go.

Thanks.

Alejandro

On Wed, Feb 16, 2011 at 10:33 AM, Mayank Bansal bansalm@yahoo-inc.com wrote:

Hi Alejandro,

We are not storing any credentials in the DB. Its just configuration like server name etc.
For XML, In my understanding if we want to change anything in extension schema we still need to refer that in workflow schema and that would change the workflow schema as well. However its a good point and we can create an issue and can take up later if its absolutely necessary.

Thanks,
Mayank 

On 2/10/11 12:37 AM, "Alejandro Abdelnur" <tucu@cloudera.com <http://tucu@cloudera.com> > wrote:

Mayank,

A couple of follow ups.
- Why do you need to store the credentials in the DB, they are in the action XML, accessible?
- Why not use the WF XML extension points (like for SLA) instead modifying the WF XML schema?

Thanks.

Alejandro

**._,_._**
Reply to sender | Reply to group | Reply via web post | Start a New Topic
Messages in this topic (16)
RECENT ACTIVITY: New Members 5
Visit Your Group
MARKETPLACE
Find useful articles and helpful tips on living with Fibromyalgia. Visit the Fibromyalgia Zone today!

Stay on top of your group activity without leaving the page you're on - Get the Yahoo! Toolbar now.

Switch to: Text-Only, Daily Digest • Unsubscribe • Terms of Use
.

**Comment by bansalmayank** [comment]
HI Alejandro,

I have some questions regarding the current SLA schema.

We have SLA_NAME_SPACE_URI = "uri:oozie:sla:0.1" hardcoded and used in the code.

So if we change the sla schema in the future then it would be changed to "uri:oozie:sla:0.2" 
1. We have to change the code to support it
2. How we are going to support multiple version of sla schema?

Thanks,
Mayank

**Comment by bansalmayank** [comment]
hi,

The code which i was referring in the previous comment, 
you can find it in 

CoordSubmitCommand.java

private void resolveSLA(Element eAppXml, CoordinatorJobBean coordJob) throws CommandException {
        // String prefix = XmlUtils.getNamespacePrefix(eAppXml,
        // SchemaService.SLA_NAME_SPACE_URI);
        Element eSla = eAppXml.getChild("action", eAppXml.getNamespace()).getChild("info",
                                                                                   Namespace.getNamespace(SchemaService.SLA_NAME_SPACE_URI));

**Comment by anew** [comment]
Alejandro,

I am coming back to your earlier comment:
- ...the WF schema does not care of what goes in the extension schema, so changes in the extension schema do not affect the WF schema. That is the whole point of using extensions.  

Strictly speaking, that means the schema for actions should also be in a separate xsd, because the workflow schema does not change if the action schema changes, right?

The question here is, what do you consider an "extension"? It seems that using schema extensions makes most sense if the extension is defined by a third party (that is not under control of the party that defines the main schema). And in that case, the schema extension should be accompanied by a library that knows how to parse the extension, and provides a well-defined API to interact with it. 

That is not the case here, and by the way, it is not the case for the SLA extension either - in current Oozie, if the SLA schema changes, Oozie core code has to change. I do believe that you know better than I why it was done this way for SLA, so please help me understand if I am missing something.

So, for the sake of code simplicity, I would prefer to add the authentication to the workflow schema, and _not_ define a new extension a a separate xsd. 

-Andreas.

**Comment by tucu00** [comment]
Extensions were added to allow users to annotate their WF with additional information Oozie does not care about.

SLA handling was a one off as it was special (Oozie had to do something). With Authentication the same thing happens.

You are correct, Oozie does not have an API to handle extensions.

I think a cleaner way is to add an API to handle extensions.

And yes, all actions should be extensions as they evolve much faster than the WF itself.

**Comment by angeloh** [comment]
Closed by 71e9c11858c1cd4faaf01a2b6251cbb3774cde40 Adding Credentials Module.

**Comment by anew** [comment]
Adding this eMail thread for reference -Andreas.

Hi Alejandro,

Please excuse the lack of communication on this issue - Angelo's commit happened under the assumption that I would follow-up with you concurrently. I was busy with other work last week and did not have enough time to lead a meaningful discussion. 

You are raising a valid point that features that do not impact the workflow engine itself should be implemented as an extension. However, Oozie currently has no good framework to support such extensions. The precedence case (the SLA extension) is not a good example, because even though the schema is defined as an extension with its own namespace, the code to parse it and to actually implement its functionality is not an extension - instead it is embedded tightly in the core Oozie code. 

I agree that we should develop a good extension framework for Oozie, and gradually migrate various features from the core to extensions. But as of today we don't have that framework. We did not want to wait with the commit of this feature until such a framework is in place. The reason why we want to move forward is that this code already is in production at Yahoo!, and we would like to close the gap between the Yahoo! release and the github release of Oozie.

Going forward, we are committed to do all future work in the Open Source and together with the community. 

-Andreas.

---

On 3/13/11 12:21 AM, "Alejandro Abdelnur" tucu@cloudera.com wrote:

Angelo, Yahoo Oozie team,

I'm a bit puzzled by this commit.

We were having a discussion in the issue and we didn't reach an agreement yet.

It would be great to understand how Yahoo is planning to work with the
community.

I know that Yahoo can do commit then review. However, if you are
asking for feedback on an issue and you are engaging in a discussion
you should take the discussion to a closure before committing the
patch. Otherwise you are wasting the time of the people that
participate in the discussion and discouraging participation.

Thanks.

Alejandro
