### ISSUE TITLE
Serialization/deserialization of WorkflowInstance

### ISSUE THREAD

**Issue by mislam77-zz** [YahooArchive/oozie#558]
Oozie team at yahoo has recently experienced multiple production issues when a new oozie version is upgraded attributed to the modifications of Workflow tables' structure.

More specifically, we added a new field into workflow table. Hence, for example, if a user submits a WF job in earlier oozie version and if the job is still active after the upgrade, oozie fails to de-serialize the WFInstance object. In other words, the object was originally serialized using the old structure whereas oozie tries to deserailize using the new structures after the upgrade. Therefore it throws exception.

Some observations that came up from our internal discussion:
1. Is it required to store the blob into table? Can't we create the the object from the other fields of the table? I know it might not be that straight forward. However, other options might be worse than this.
2. If we want to keep the blob, the new field(s) should be added at the end during serialization. However if some fields are removed, how could we handle that? Might not be a flexible idea.
3. During serialization, we could use some type of version at the beginning, that would help to de-serailize the object. This might make the coding very ugly depending on how many old versions we would like to support.  
4. Since it is a very well-known problem, there should be some standard procedure. However they might not be easy too.

Anyway these are just the initial thoughts. We didn't come up in any conclusion yet.
Please feel free to make comment?

Thanks,
Mohammad

**Comment by tucu00** [comment]
there are different options:

1 \* (as you say) use a version VERSION field. This means that Oozie will be able to handle more than one version o WF state. This also means that Oozie should be able to deserialize  blob from another version to check the VERSION field. This also means the current serialialization probably won't works as it is binary (Writable) and assumes it can be fully read. so we should change to a serialization format that allows the inspection of the VERSION without having to deserialize the whole thing. Using JSON would do the trick.

2\* Have a migration script that gets a DB from Oozie version N and copies/converts things into a new DB for Oozie version N+1.

IMO, we should aim for #1, but we'll have to do #2 once before getting to #1.

**Comment by topher-zicornell** [comment]
Hi,

I'd like to point out that using blobs in a database breaks First Normal Form.  By doing so, it introduces all kinds of limitations and frustrations.  I recently worked on a project which did exactly that, and am still haunted by the nightmares.

Tucu, could you (or somebody) comment on the importance of blobs being blobs (rather than database fields) in Oozie?  Is that something we could consider designing away from, or is it here to stay?

.  Topher

**Comment by tucu00** [comment]
Topher,

The blobs are workflow job state-machine state. Their contents are not used outside of the workflow library. They are completely opaque to the rest of the system.

Alejandro

**Comment by topher-zicornell** [comment]
Hi,

Erm... I'm not convinced that reason is strong enough to glom it away in a blob.  But, let's put that aside for the moment.  It's a blob, like image data or something.  Ok.

Regarding JSON serializations.  On the surface it looks like a simple and straight-forward little trick.  But we used this heavily in a recent project and ran into some difficulties.  So, not to persuade or dissuade, but just to comment:

1) To support container objects which reference interfaces, additional metadata will need to be provided describing  the implementation class which should be used to unmarshall the object.  That can be provided through some additional code-level configuration, or XML-based configuration, or even as meta-data embedded in the JSON object itself.  Hopefully your JSON library will take care of that for you.  (Ours didn't.  Arg.)

2) Similarly, to unmarshall standard generics containers (lists, maps, etc), you'll need the same type of thing describing the generics contained.  If your container is an interface (often the case), you'll need the same type of provisions as in 1.

3) The code working with the unmarshalled objects must be tolerant of the structure from previous versions.  When a field is added in 3.2, the code should be adjusted to Do The Right Thing if that field is missing in order to support pre-3.2 items.

4) Extra fields aren't really a problem as long as your JSON library knows to ignore them.  That's usually a configuration thing.

5) When annotating a POJO for serialization, you'll want to make sure not to accidentally pull in transient data.  I've seen cases where tracking lists significantly bloated serializations and were useless once the object was reconstituted.  The bloat can cause overhead issues with the database, or at least, did in our case.

Items 1 & 2 can be a major headache to get right.

The versioning thing might be valuable depending on the circumstances and implementation, but it could just as easily become a cumbersome frustrating necessity.  I've seen that kind of scheme work well, and I've seen it flop badly.  That might merit more discussion.  How would you envision the migration step being triggered?  

.  Topher

**Comment by mislam77-zz** [comment]
Guys,
Thanks for the discussion.
As I mentioned in my original proposal #1, what are issues to make the blob into columsn in a table. If needed, we could consider to introduce a new table too.

Regards,
Mohammad

**Comment by tucu00** [comment]
Topher,

What goes in the blob is quite simple, a state machine which consists of Maps of string or string arrays. Oozie already uses JSON-Simple which it just works for what we need, so not annotations, no classes marshalling, etc, etc.

To handle versions without ser/ders version mismatch, my thought is to fetch the data as a Map, get the version entry and based on that use a different deser strategy, on re-ser the latest ser would be used.

I've played around a bit modeling this and I'm quite happy with the results.

Thanks.

Alejandro

**Comment by topher-zicornell** [comment]
Hi Mohammad,

Tucu's (sorry _Alejandro's_) argument is that the blob contains state-machine cohesive context information, and thus should be considered in it's entirety as a single item of uncrackable (from the storage perspective) data.  

He's considering it to be similar to image data, for example.  There are a bunch of different fields and data structures inside the image data, but as far as any storage mechanism is concerned, it's just an image.

I don't really agree that that's a good enough reason to break 1NF in this case.  I think it's just that Alejandro and I give differing weights to the importance of 1NF.

.  Topher

**Comment by topher-zicornell** [comment]
Hi Alejandro,

I'm glad you're happy with the model you're playing around with. ;)

Keeping the data simple definitely alleviates a lot of the pain around doing this.

If you using a map, and the data is always string-based, is there a reason for the version field?

So, my thinking is this:
- If you add a field in a later version, you'll have to also add a way to populate that field for existing entities.  In this case, no version is needed -- if the field isn't there, populate it, done.
- If you remove a field in a later version, you don't need to do anything.  Just ignore that field.
- If you change the type of a field... well, if they're always strings that would never happen.

In what other case might a version be required?

.  Topher

**Comment by tucu00** [comment]
Topher,
- Tucu/Alejandro/Alex, all are good :)
- The reason for using a blob instead a table is that the number of DB operations is much less, one read/write as opposed as multiple rows. Also frees Oozie for keeping track of the 'rows' that changed not to do identical updates.
- regarding the version field need, well logic may end up be different for different versions. that would be the main motivation.

Thanks.

Alejandro/Alex/Tucu

**Comment by topher-zicornell** [comment]
Hi Tucu,

For the blob thing, I'd like to point out that you're trading non-optimizable Java work (in the serialization and deserialization stuff) for optimizable DB work (in read/write of the additional data).  And the single row locking can still be used to gate access to the bag table (as long as it's a one to many relationship).

For the version thing, logic being different...  I've been pondering this.  Just to be clear, we're talking ONLY about deserialization for this; not the state-machine itself, right?  If so, the only logic I can think of is type conversion.  (I mentioned that up above.)

If the fields are all simple strings or containers of strings, what other logic might there be?

At any rate, I've shared all the bits I felt were important about this.  ;)

.  Topher

**Comment by tucu00** [comment]
Topher,

[I like this kind of discussions, normally help to make things better]

fields are simple string/containers of .., correct. but still the processing logic of the workflow engine may have changed and uses additional fields to (for example) do some optimization or extra checks, if the version is CURRENT-1 it would know that those fields are not avail and it would not attempt the optimization or extra check.

**Comment by mislam77-zz** [comment]
What about store a key=value pair for all the DB columns? Store and load could take care of that parsing. Extra spaces could be reduced by using a number instead of string as key.

Version idea might be a overkill. Because for every version there should be a separate serialization /de-serialization routines.

**Comment by topher-zicornell** [comment]
Hi Mohammad,

You'd only need distinct deserialization routines per version, not serialization.  And they can be hierarchical, like an object hierarchy (version 3.3 extends 3.2 and just does the delta work needed).  

I would prefer an attribute (key-value pair) table to blobs, but even if you did that you'd probably want to do the versioning thing just to allow for the algorithmic changes to the interpretation of the fields.

Using a number instead of a key in the attribute table would be dangerous.  I'd recommend against that.  It makes the definitions a bit magical, like runes.  Somebody trying to work with the data would just have to Know what's what.

You could have a translation table of numbers to keys, but then you'd be constantly doing a join to get the key names out.  I'm not sure which would be better for the DB, keys right in the table, or joins on all the queries?

.  Topher

**Comment by angeloh** [comment]
The discussion has moved to http://oozie-jira.hadoop.developer.yahoo.net/browse/OOZIE-104.
