### ISSUE TITLE
input data check should have a  timeout for catch-up mode too.

### ISSUE THREAD

**Issue by marcychen** [YahooArchive/oozie#67]
For normal,timeout when  Nominal Time + timeout > current time 
For catchup,timeout when  Created Time + timeout > current time

**Comment by mislam77-zz** [comment]
Since it will take sometime to find a suitable timeout for the "catch-up" job, I think we coul provide a catchup-timeout that user would optionally provide through coordinator.xml. BTW there is already a "timeout" element in current XML which determines the timeout of  current/regular/normal jobs.

Comment?

**Comment by anew** [comment]
Although "normal" and "catchup" jobs are actually treated equally by Oozie, I think there is a true difference in use cases:
- A catchup job is started to run/redo computations whose nominal time is often far back in the past, and the input data is typically historical data and already available at the creation time of the job. But most likely the catchup also requires many more jobs to be run than for current computations.
- A current job has data dependencies on other jobs that have just finished or are expected to finish very soon. If any of these jobs are late, then this job has to wait. This is more likely to happen than in catchup mode.

Therefore, it is desirable to get expire a catchup job sooner than a current job. On the other hand, for simplicity's sake, and because Oozie currently does not have an explicit notion of "catchup", it is desirable to have the same timeout for both types of jobs.

I do not have a strong preference, but a slight tendency towards keeping it simple. So for now, I vote for a single timeout which kicks in when max(Nominal Time, Created Time) + timeout >  Current Time.

**Comment by mislam77-zz** [comment]
We can identify the job as "catchup" by checking  creationTime > nominalTime. 
In that case, I prefer to use this :
Catchup Timeout = Creation Time  + Concurrency \* Timeout

Concurrency means how many max job could be in WAITING state or data checking state. 

Overall the reason is: if there are concurrency = 5 )say), there will be at most 5 actions actively checking for their data. Now if they have chain/ripple dependency, the last one has to wait until the other 4 are finished. 

To accommodate this command scenario, I want to give a relax/loose timeout.

Comments?

**Comment by angeloh** [comment]
Closed by 821aaaa9121ca2b8218cc35f2f02e4e1df9439f2 input data check should have a timeout for catch-up mode
