### ISSUE TITLE
Option to rerun from failed node.

### ISSUE THREAD

**Issue by marcychen** [YahooArchive/oozie#78]
Oozie will provide a mechanism for customers to retry a failed action within a workflow. If the action is successful, the dependent action(s) will be executed as well.

**Comment by mislam77-zz** [comment]
We plan to provide another client utility (at bin/) for this functionality.

Details:
- We will write a Java class that will call to oozie server WS API twice
  - First time , to get the job info.
  - second time, to rerun with appropriate  "skipNodes" option.
- This java class will be invoked from the wrapper script oozie_wf_rerun.sh

**Comment by mislam77-zz** [comment]
What will be the good option?
- provide a script in client package in dir bin/. Cons: We might end up supporting/enhancing the code in the long run.
- Provide as a Client utility/example and it is user responsibility to maintain.
- as part of our example package.

Comments?

**Comment by tucu00** [comment]
- When you say 'failed action' you mean an action that ended in ERROR? If so, a workflow could have multiple of such actions and alternate executions paths because of them. How things would be handled then?
- Why a different CLI? Why not a new option for the 'oozie job' command?

**Comment by anew** [comment]
I am not sure why this should be implemented in a client. 
I would prefer implementing a "retry workflow" in the Oozie core.

**Comment by mislam77-zz** [comment]
This was the original proposal around 10 months back in yahoo: support it into oozie core.

However, the counter proposal was not to support in oozie supported code. Because there is already a work-around where user can follow these two steps: 
- At first call, get all the succeeded actions using something like "oozie job -info <id>" and then parsing.
- Secondly call oozie rerun after setting skipnodes as the all successful actions.

Vase on this logic, we discussed to provide a utility for the customer to combine these two steps into one as reference only(i.e. not supportable)

Do you think that logic doesn't hold anymore.

Comments.

**Comment by anew** [comment]
The Oozie client is a thin client. Thus this belongs in the server not the client.

**Comment by mislam77-zz** [comment]
So Andreas vote is to support in the server. 
In that case, from client side, I prefer to use the current oozie rerun option with an extra flag to rerun from the failed node. So there will be less changes from the WS API side too.

I need to close this discussion soon.
Please comment.

**Comment by bansalmayank** [comment]
Closed by 8d5bcbffbc25bbb734ef4113e55cc99621d9c5b9 Option to rerun from failed node.
